update github workflow

diff --git a/.github/workflows/docker-ecr.yml b/.github/workflows/docker-ecr.yml
--- a/.github/workflows/docker-ecr.yml
+++ b/.github/workflows/docker-ecr.yml
@@ -18,6 +18,13 @@ jobs:
       - name: Load account id
         env:
           AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+        run: |
+          if [ -f .env ]; then
+            export $(cat .env | xargs)
+          else
+            echo "AWS account id not found!"
+            exit 1
+          fi
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -25,6 +32,7 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
+          aws-account-id:
 
       - name: Login to Amazon ECR
         id: ecr-login
